name: RPM Build and Install Test Workflow
on: 
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'Branch to Build RPM From'
        required: true
      centos_ver:
        type: string
        description: 'Centos Base image (options: 8/9) - Optional, default is 9'
        default: '9'
  
jobs:
  rpm-build-and-and-install-test-base:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
     
      - name: Run Non Containerized RPM Build And Install Test
        run: |
            make rpm-build-and-install-test BUILD_S3SELECT=0 CENTOS_VER=${{ inputs.centos_ver }} CONTAINER_PLATFORM=linux/amd64

