name: RPM Build And Upload Flow
on: 
  workflow_call:
    inputs:
      branch: 
        type: string
        description: 'Run rpm build and upload to aws flow'
        default: 'master'

jobs:
  build-rpm-centos8:
    uses: ./.github/workflows/rpm-build-base.yaml
    with:
      branch: ${{ inputs.branch }}
      centos_ver: '8'

  build-rpm-centos9:
    uses: ./.github/workflows/rpm-build-base.yaml
    with:
      branch: ${{ inputs.branch }}
      centos_ver: '9'
  
  build-rpm-centos8-ppc64le:
    uses: ./.github/workflows/rpm-build-base.yaml
    with:
      branch: ${{ inputs.branch }}
      centos_ver: '8'
      architecture: 'linux/ppc64le'

  build-rpm-centos9-ppc64le:
    uses: ./.github/workflows/rpm-build-base.yaml
    with:
      branch: ${{ inputs.branch }}
      centos_ver: '9'
      architecture: 'linux/ppc64le'

  upload-centos8-rpm-to-aws:
    needs: build-rpm-centos8
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: ${{ needs.build-rpm-centos8.outputs.rpm_full_path }}
    secrets: inherit

  upload-centos9-rpm-to-aws:
    needs: build-rpm-centos9
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: ${{ needs.build-rpm-centos9.outputs.rpm_full_path }}
    secrets: inherit
  
  upload-centos8-ppc64le-rpm-to-aws:
    needs: build-rpm-centos8-ppc64le
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: ${{ needs.build-rpm-centos8-ppc64le.outputs.rpm_full_path }}
    secrets: inherit

  upload-centos9-ppc64le-rpm-to-aws:
    needs: build-rpm-centos9-ppc64le
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: ${{ needs.build-rpm-centos9-ppc64le.outputs.rpm_full_path }}
    secrets: inherit
