  name: Upload RPM to AWS
  on: 
    workflow_call:
      inputs:
        rpm_full_path: 
          type: string
          description: 'RPM path to be uploaded to AWS bucket'


  jobs:
    upload-rpm-to-aws:
      runs-on: ubuntu-latest
      timeout-minutes: 90
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.rpm_full_path }}

        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.NEWAWSPROJKEY }}
            aws-secret-access-key: ${{ secrets.NEWAWSPROJSECRET }}
            aws-region: us-east-1

        - name: Copy RPM to S3 bucket
          run: |
            aws s3 cp ${{ inputs.rpm_full_path }} s3://noobaa-core-rpms/
